Get rid of gr::random so it can be compiled with c++17
The error was:

In file included from
/Users/carlesfernandez/git/cttc/src/algorithms/signal_generator/gnuradio_blocks/signal_generator_c.cc:31:
In file included from
/Users/carlesfernandez/git/cttc/src/algorithms/signal_generator/gnuradio_blocks/signal_generator_c.h:36:
In file included from /opt/local/include/gnuradio/random.h:30:
In file included from /opt/local/include/boost/random.hpp:83:
/opt/local/include/boost/random/uniform_on_sphere.hpp:229:37: error: no
member named 'bind2nd' in namespace 'std'
        std::bind2nd(std::multiplies<RealType>(), 1/sqrt(sqsum)));
                               ~~~~~^
1 error generated.